### ISSUE TITLE
Artshitliste

### ISSUE THREAD

**Issue by JKSheard** [davidkonrad/myrejagten#4]
Hej David,

Jeg tror i øjeblikket artshitlisten tæller antallet af baitcards som myrerne er fundet på og ikke antallet af eksperimenter.

Der står nemlig at sort havemyre er fundet på 40 eksperimenter, men jeg har altså kun analyseret 18. 
Er det muligt at ændre den så det vises pr lokalitet/myre id/eksperiment og ikke pr lokkemad?

**Comment by davidkonrad** [comment]
@JKSheard Super du følger op! Jeg kigger på det i weekenden.
