### ISSUE TITLE
Mail sendes ved tast enter

### ISSUE THREAD

**Issue by JKSheard** [davidkonrad/myrejagten#7]
Hej David,

Jeg er efterhånden super frustreret over det her.
Alt for ofte sker det, at mens jeg er i gang med at skrive en mail til en bruger og trykker enter for at skifte linjer, så bliver min mail sendt. 

Jeg er næsten bange for at bruge enter tasten nu da folk ender med op til 4 ufærdige mails før det kan lade sig gøre for mig at skrive den færdig.

**Comment by davidkonrad** [comment]
Hvilken browser bruger du, når du oplever dette?

**Comment by JKSheard** [comment]
Chrome

**Comment by davidkonrad** [comment]
Det burde ikke kunne ske.. Det du beskriver er et `<form>` element der er sammen med en `<submit>`.  Jeg bruger slet ikke forme i myrejagten og helt sikkert ikke submit-knapper.  Ting kan kun ske hvis man aktivt klikker på en knap, ikke fordi man kommer til at hitte enter.

**Comment by davidkonrad** [comment]
Jeg troor det er dig der er problemet :)

**Comment by JKSheard** [comment]
Det er meget muligt det ikke burde kunne ske. Men det sker. Igen for 1 minut siden. Når jeg prøver at lave et nyt afsnit mellem to linjer tekst, og ikke trykker på noget som helst andet end enter, så sender den min mail. Det er ikke i alle mails det sker, men det sker tilpas ofte.
